/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal.java
 *
 * Created on 20/09/2011, 13:59:40
 */

package br.interfaces;

/**
 *
 * @author william
 */
public class Principal extends javax.swing.JFrame {

    /** Creates new form Principal */
    public Principal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        btnCadastraTarefa = new javax.swing.JButton();
        btnConfigurar = new javax.swing.JButton();
        btnResolvido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Event");
        setResizable(false);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Table);

        jScrollPane1.setBounds(210, 10, 440, 440);
        Desktop.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnCadastraTarefa.setText("Cadastrar Tarefa");
        btnCadastraTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraTarefaActionPerformed(evt);
            }
        });
        btnCadastraTarefa.setBounds(10, 10, 150, 30);
        Desktop.add(btnCadastraTarefa, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnConfigurar.setText("Configurar");
        btnConfigurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigurarActionPerformed(evt);
            }
        });
        btnConfigurar.setBounds(10, 320, 140, 30);
        Desktop.add(btnConfigurar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnResolvido.setText("Resolvido");
        btnResolvido.setBounds(660, 10, 90, 30);
        Desktop.add(btnResolvido, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastraTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraTarefaActionPerformed
        // TODO add your handling code here:
        Tarefa tarefa = new Tarefa();
        Desktop.add(tarefa);
        tarefa.show();
    }//GEN-LAST:event_btnCadastraTarefaActionPerformed

    private void btnConfigurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigurarActionPerformed
        // TODO add your handling code here:
        Configurar configurar = new Configurar();
        Desktop.add(configurar);
        configurar.show();
    }//GEN-LAST:event_btnConfigurarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JTable Table;
    private javax.swing.JButton btnCadastraTarefa;
    private javax.swing.JButton btnConfigurar;
    private javax.swing.JButton btnResolvido;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
